=== mulesoft/jubula-accessibility/org.mule.tooling.jubula.extensions/resources/xml/ToolkitComponentConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:include schemaLocation="CommonComponentConfiguration.xsd" />
	<xs:element name="compSystem">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="configVersion" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="abstractComponent" />
					<xs:element ref="toolkitComponent" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="configVersion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="majorVersion" />
				<xs:element ref="minorVersion" />
				<xs:element ref="majorCustomVersion" />
				<xs:element ref="minorCustomVersion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="majorVersion" type="xs:string" />
	<xs:element name="minorVersion" type="xs:string" />
	<xs:element name="majorCustomVersion" type="xs:string" />
	<xs:element name="minorCustomVersion" type="xs:string" />
	<xs:element name="toolkitComponent">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="defaultMapping" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="realizes" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="extends" />
				<xs:element ref="testerClass" />
				<xs:element minOccurs="0" maxOccurs="1" ref="componentClass" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="action" />
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:ID" />
			<xs:attribute name="visible" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="observable" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="changed" />
			<xs:attribute name="deprecated">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="abstractComponent">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="realizes" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="extends" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="action" />
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:ID" />
			<xs:attribute name="visible" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true" />
						<xs:enumeration value="false" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="changed" />
			<xs:attribute name="deprecated">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="testerClass" type="xs:string" />
	<xs:element name="componentClass">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="property" />
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="value" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element></xs:schema>

=== mulesoft/jubula-accessibility/org.eclipse.jubula.examples.extension.rcp.toolkit/resources/xml/MyComponentConfiguration.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!--
    Copyright (c) 2004, 2010 BREDEX GmbH.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
 -->

<!--CAUTION: don?t format any entries, especially don?t use line breaks!
	The value of the formated item may contain formating characters like
	tabs or newlines, making them unusable for class or data lookup!-->
<compSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ToolkitComponentConfiguration.xsd">
	<configVersion>
		<majorVersion>1</majorVersion>
		<minorVersion>38</minorVersion>
		<majorCustomVersion>0</majorCustomVersion>
		<minorCustomVersion>0</minorCustomVersion>
	</configVersion>

	<toolkitComponent type="org.eclipse.swt.widgets.Group" visible="true">
		<realizes>guidancer.abstract.Widget</realizes>
		<testerClass>org.eclipse.jubula.rc.swt.implclasses.GroupImplClass</testerClass>
		<componentClass name="org.eclipse.swt.widgets.Group" />
	</toolkitComponent>

</compSystem>
